# Generated by Django 3.2.19 on 2023-06-20 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_rename_contact_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
